name: audioplayers_platform_interface
description: The platform interface for audioplayers, a Flutter plugin to play multiple audio files simultaneously
version: 6.1.0
publish_to: none
homepage: https://github.com/bluefireteam/audioplayers
repository: https://github.com/bluefireteam/audioplayers/tree/master/packages/audioplayers_platform_interface

dependencies:
  collection: ^1.17.2
  flutter:
    sdk: flutter
  meta: ^1.9.1
  plugin_platform_interface:
    git: https://github.com/kumsumit/plugin_platform_interface.git

dev_dependencies:
  dartdoc: ^7.0.2
  flame_lint: ^1.1.1
  flutter_test:
    sdk: flutter

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=3.13.0'
